// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: arm.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Reachy.Part.Arm {
  public static partial class ArmService
  {
    static readonly string __ServiceName = "reachy.part.arm.ArmService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ListOfArm> __Marshaller_reachy_part_arm_ListOfArm = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ListOfArm.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.PartId> __Marshaller_reachy_part_PartId = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.PartId.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmState> __Marshaller_reachy_part_arm_ArmState = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmState.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmFKRequest> __Marshaller_reachy_part_arm_ArmFKRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmFKRequest.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmFKSolution> __Marshaller_reachy_part_arm_ArmFKSolution = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmFKSolution.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmIKRequest> __Marshaller_reachy_part_arm_ArmIKRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmIKRequest.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmIKSolution> __Marshaller_reachy_part_arm_ArmIKSolution = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmIKSolution.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmCartesianGoal> __Marshaller_reachy_part_arm_ArmCartesianGoal = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmCartesianGoal.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmJointGoal> __Marshaller_reachy_part_arm_ArmJointGoal = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmJointGoal.Parser));
    static readonly grpc::Marshaller<global::Reachy.Kinematics.Matrix4x4> __Marshaller_reachy_kinematics_Matrix4x4 = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Kinematics.Matrix4x4.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmPosition> __Marshaller_reachy_part_arm_ArmPosition = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmPosition.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmStatus> __Marshaller_reachy_part_arm_ArmStatus = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmStatus.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmLimits> __Marshaller_reachy_part_arm_ArmLimits = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmLimits.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.ArmTemperatures> __Marshaller_reachy_part_arm_ArmTemperatures = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.ArmTemperatures.Parser));
    static readonly grpc::Marshaller<global::Reachy.Part.Arm.SpeedLimitRequest> __Marshaller_reachy_part_arm_SpeedLimitRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Part.Arm.SpeedLimitRequest.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Reachy.Part.Arm.ListOfArm> __Method_GetAllArms = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Reachy.Part.Arm.ListOfArm>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllArms",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_reachy_part_arm_ListOfArm);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmState> __Method_GetState = new grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmState>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetState",
        __Marshaller_reachy_part_PartId,
        __Marshaller_reachy_part_arm_ArmState);

    static readonly grpc::Method<global::Reachy.Part.Arm.ArmFKRequest, global::Reachy.Part.Arm.ArmFKSolution> __Method_ComputeArmFK = new grpc::Method<global::Reachy.Part.Arm.ArmFKRequest, global::Reachy.Part.Arm.ArmFKSolution>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ComputeArmFK",
        __Marshaller_reachy_part_arm_ArmFKRequest,
        __Marshaller_reachy_part_arm_ArmFKSolution);

    static readonly grpc::Method<global::Reachy.Part.Arm.ArmIKRequest, global::Reachy.Part.Arm.ArmIKSolution> __Method_ComputeArmIK = new grpc::Method<global::Reachy.Part.Arm.ArmIKRequest, global::Reachy.Part.Arm.ArmIKSolution>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ComputeArmIK",
        __Marshaller_reachy_part_arm_ArmIKRequest,
        __Marshaller_reachy_part_arm_ArmIKSolution);

    static readonly grpc::Method<global::Reachy.Part.Arm.ArmCartesianGoal, global::Google.Protobuf.WellKnownTypes.Empty> __Method_GoToCartesianPosition = new grpc::Method<global::Reachy.Part.Arm.ArmCartesianGoal, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GoToCartesianPosition",
        __Marshaller_reachy_part_arm_ArmCartesianGoal,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Reachy.Part.Arm.ArmJointGoal, global::Google.Protobuf.WellKnownTypes.Empty> __Method_GoToJointPosition = new grpc::Method<global::Reachy.Part.Arm.ArmJointGoal, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GoToJointPosition",
        __Marshaller_reachy_part_arm_ArmJointGoal,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Reachy.Kinematics.Matrix4x4> __Method_GetCartesianPosition = new grpc::Method<global::Reachy.Part.PartId, global::Reachy.Kinematics.Matrix4x4>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCartesianPosition",
        __Marshaller_reachy_part_PartId,
        __Marshaller_reachy_kinematics_Matrix4x4);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmPosition> __Method_GetJointPosition = new grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmPosition>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetJointPosition",
        __Marshaller_reachy_part_PartId,
        __Marshaller_reachy_part_arm_ArmPosition);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmStatus> __Method_Audit = new grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmStatus>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Audit",
        __Marshaller_reachy_part_PartId,
        __Marshaller_reachy_part_arm_ArmStatus);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_HeartBeat = new grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HeartBeat",
        __Marshaller_reachy_part_PartId,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Restart = new grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Restart",
        __Marshaller_reachy_part_PartId,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ResetDefaultValues = new grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResetDefaultValues",
        __Marshaller_reachy_part_PartId,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TurnOn = new grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TurnOn",
        __Marshaller_reachy_part_PartId,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TurnOff = new grpc::Method<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TurnOff",
        __Marshaller_reachy_part_PartId,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmLimits> __Method_GetJointsLimits = new grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmLimits>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetJointsLimits",
        __Marshaller_reachy_part_PartId,
        __Marshaller_reachy_part_arm_ArmLimits);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmTemperatures> __Method_GetTemperatures = new grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmTemperatures>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTemperatures",
        __Marshaller_reachy_part_PartId,
        __Marshaller_reachy_part_arm_ArmTemperatures);

    static readonly grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmPosition> __Method_GetJointGoalPosition = new grpc::Method<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmPosition>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetJointGoalPosition",
        __Marshaller_reachy_part_PartId,
        __Marshaller_reachy_part_arm_ArmPosition);

    static readonly grpc::Method<global::Reachy.Part.Arm.SpeedLimitRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetSpeedLimit = new grpc::Method<global::Reachy.Part.Arm.SpeedLimitRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetSpeedLimit",
        __Marshaller_reachy_part_arm_SpeedLimitRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Reachy.Part.Arm.ArmReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ArmService</summary>
    [grpc::BindServiceMethod(typeof(ArmService), "BindService")]
    public abstract partial class ArmServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ListOfArm> GetAllArms(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ArmState> GetState(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ArmFKSolution> ComputeArmFK(global::Reachy.Part.Arm.ArmFKRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ArmIKSolution> ComputeArmIK(global::Reachy.Part.Arm.ArmIKRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> GoToCartesianPosition(global::Reachy.Part.Arm.ArmCartesianGoal request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> GoToJointPosition(global::Reachy.Part.Arm.ArmJointGoal request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Kinematics.Matrix4x4> GetCartesianPosition(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ArmPosition> GetJointPosition(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ArmStatus> Audit(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeat(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Restart(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> ResetDefaultValues(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> TurnOn(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> TurnOff(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ArmLimits> GetJointsLimits(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ArmTemperatures> GetTemperatures(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Part.Arm.ArmPosition> GetJointGoalPosition(global::Reachy.Part.PartId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SetSpeedLimit(global::Reachy.Part.Arm.SpeedLimitRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ArmService</summary>
    public partial class ArmServiceClient : grpc::ClientBase<ArmServiceClient>
    {
      /// <summary>Creates a new client for ArmService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ArmServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ArmService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ArmServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ArmServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ArmServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Reachy.Part.Arm.ListOfArm GetAllArms(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllArms(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ListOfArm GetAllArms(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllArms, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ListOfArm> GetAllArmsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllArmsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ListOfArm> GetAllArmsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllArms, null, options, request);
      }
      public virtual global::Reachy.Part.Arm.ArmState GetState(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ArmState GetState(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmState> GetStateAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmState> GetStateAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetState, null, options, request);
      }
      public virtual global::Reachy.Part.Arm.ArmFKSolution ComputeArmFK(global::Reachy.Part.Arm.ArmFKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeArmFK(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ArmFKSolution ComputeArmFK(global::Reachy.Part.Arm.ArmFKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ComputeArmFK, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmFKSolution> ComputeArmFKAsync(global::Reachy.Part.Arm.ArmFKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeArmFKAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmFKSolution> ComputeArmFKAsync(global::Reachy.Part.Arm.ArmFKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ComputeArmFK, null, options, request);
      }
      public virtual global::Reachy.Part.Arm.ArmIKSolution ComputeArmIK(global::Reachy.Part.Arm.ArmIKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeArmIK(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ArmIKSolution ComputeArmIK(global::Reachy.Part.Arm.ArmIKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ComputeArmIK, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmIKSolution> ComputeArmIKAsync(global::Reachy.Part.Arm.ArmIKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeArmIKAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmIKSolution> ComputeArmIKAsync(global::Reachy.Part.Arm.ArmIKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ComputeArmIK, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GoToCartesianPosition(global::Reachy.Part.Arm.ArmCartesianGoal request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GoToCartesianPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GoToCartesianPosition(global::Reachy.Part.Arm.ArmCartesianGoal request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GoToCartesianPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GoToCartesianPositionAsync(global::Reachy.Part.Arm.ArmCartesianGoal request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GoToCartesianPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GoToCartesianPositionAsync(global::Reachy.Part.Arm.ArmCartesianGoal request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GoToCartesianPosition, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GoToJointPosition(global::Reachy.Part.Arm.ArmJointGoal request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GoToJointPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GoToJointPosition(global::Reachy.Part.Arm.ArmJointGoal request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GoToJointPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GoToJointPositionAsync(global::Reachy.Part.Arm.ArmJointGoal request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GoToJointPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GoToJointPositionAsync(global::Reachy.Part.Arm.ArmJointGoal request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GoToJointPosition, null, options, request);
      }
      public virtual global::Reachy.Kinematics.Matrix4x4 GetCartesianPosition(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCartesianPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Kinematics.Matrix4x4 GetCartesianPosition(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCartesianPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Kinematics.Matrix4x4> GetCartesianPositionAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCartesianPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Kinematics.Matrix4x4> GetCartesianPositionAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCartesianPosition, null, options, request);
      }
      public virtual global::Reachy.Part.Arm.ArmPosition GetJointPosition(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJointPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ArmPosition GetJointPosition(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetJointPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmPosition> GetJointPositionAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJointPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmPosition> GetJointPositionAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetJointPosition, null, options, request);
      }
      public virtual global::Reachy.Part.Arm.ArmStatus Audit(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Audit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ArmStatus Audit(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Audit, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmStatus> AuditAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AuditAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmStatus> AuditAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Audit, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty HeartBeat(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HeartBeat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty HeartBeat(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HeartBeat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeatAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HeartBeatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeatAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HeartBeat, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Restart(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Restart(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Restart(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Restart, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RestartAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RestartAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RestartAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Restart, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty ResetDefaultValues(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResetDefaultValues(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty ResetDefaultValues(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ResetDefaultValues, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ResetDefaultValuesAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResetDefaultValuesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ResetDefaultValuesAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ResetDefaultValues, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty TurnOn(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TurnOn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty TurnOn(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TurnOn, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TurnOnAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TurnOnAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TurnOnAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TurnOn, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty TurnOff(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TurnOff(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty TurnOff(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TurnOff, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TurnOffAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TurnOffAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TurnOffAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TurnOff, null, options, request);
      }
      public virtual global::Reachy.Part.Arm.ArmLimits GetJointsLimits(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJointsLimits(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ArmLimits GetJointsLimits(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetJointsLimits, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmLimits> GetJointsLimitsAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJointsLimitsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmLimits> GetJointsLimitsAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetJointsLimits, null, options, request);
      }
      public virtual global::Reachy.Part.Arm.ArmTemperatures GetTemperatures(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTemperatures(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ArmTemperatures GetTemperatures(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTemperatures, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmTemperatures> GetTemperaturesAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTemperaturesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmTemperatures> GetTemperaturesAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTemperatures, null, options, request);
      }
      public virtual global::Reachy.Part.Arm.ArmPosition GetJointGoalPosition(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJointGoalPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Part.Arm.ArmPosition GetJointGoalPosition(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetJointGoalPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmPosition> GetJointGoalPositionAsync(global::Reachy.Part.PartId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJointGoalPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Part.Arm.ArmPosition> GetJointGoalPositionAsync(global::Reachy.Part.PartId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetJointGoalPosition, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SetSpeedLimit(global::Reachy.Part.Arm.SpeedLimitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetSpeedLimit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SetSpeedLimit(global::Reachy.Part.Arm.SpeedLimitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetSpeedLimit, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SetSpeedLimitAsync(global::Reachy.Part.Arm.SpeedLimitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetSpeedLimitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SetSpeedLimitAsync(global::Reachy.Part.Arm.SpeedLimitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetSpeedLimit, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ArmServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ArmServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ArmServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllArms, serviceImpl.GetAllArms)
          .AddMethod(__Method_GetState, serviceImpl.GetState)
          .AddMethod(__Method_ComputeArmFK, serviceImpl.ComputeArmFK)
          .AddMethod(__Method_ComputeArmIK, serviceImpl.ComputeArmIK)
          .AddMethod(__Method_GoToCartesianPosition, serviceImpl.GoToCartesianPosition)
          .AddMethod(__Method_GoToJointPosition, serviceImpl.GoToJointPosition)
          .AddMethod(__Method_GetCartesianPosition, serviceImpl.GetCartesianPosition)
          .AddMethod(__Method_GetJointPosition, serviceImpl.GetJointPosition)
          .AddMethod(__Method_Audit, serviceImpl.Audit)
          .AddMethod(__Method_HeartBeat, serviceImpl.HeartBeat)
          .AddMethod(__Method_Restart, serviceImpl.Restart)
          .AddMethod(__Method_ResetDefaultValues, serviceImpl.ResetDefaultValues)
          .AddMethod(__Method_TurnOn, serviceImpl.TurnOn)
          .AddMethod(__Method_TurnOff, serviceImpl.TurnOff)
          .AddMethod(__Method_GetJointsLimits, serviceImpl.GetJointsLimits)
          .AddMethod(__Method_GetTemperatures, serviceImpl.GetTemperatures)
          .AddMethod(__Method_GetJointGoalPosition, serviceImpl.GetJointGoalPosition)
          .AddMethod(__Method_SetSpeedLimit, serviceImpl.SetSpeedLimit).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ArmServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllArms, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Reachy.Part.Arm.ListOfArm>(serviceImpl.GetAllArms));
      serviceBinder.AddMethod(__Method_GetState, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmState>(serviceImpl.GetState));
      serviceBinder.AddMethod(__Method_ComputeArmFK, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.Arm.ArmFKRequest, global::Reachy.Part.Arm.ArmFKSolution>(serviceImpl.ComputeArmFK));
      serviceBinder.AddMethod(__Method_ComputeArmIK, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.Arm.ArmIKRequest, global::Reachy.Part.Arm.ArmIKSolution>(serviceImpl.ComputeArmIK));
      serviceBinder.AddMethod(__Method_GoToCartesianPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.Arm.ArmCartesianGoal, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.GoToCartesianPosition));
      serviceBinder.AddMethod(__Method_GoToJointPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.Arm.ArmJointGoal, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.GoToJointPosition));
      serviceBinder.AddMethod(__Method_GetCartesianPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Reachy.Kinematics.Matrix4x4>(serviceImpl.GetCartesianPosition));
      serviceBinder.AddMethod(__Method_GetJointPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmPosition>(serviceImpl.GetJointPosition));
      serviceBinder.AddMethod(__Method_Audit, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmStatus>(serviceImpl.Audit));
      serviceBinder.AddMethod(__Method_HeartBeat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.HeartBeat));
      serviceBinder.AddMethod(__Method_Restart, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Restart));
      serviceBinder.AddMethod(__Method_ResetDefaultValues, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.ResetDefaultValues));
      serviceBinder.AddMethod(__Method_TurnOn, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.TurnOn));
      serviceBinder.AddMethod(__Method_TurnOff, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.TurnOff));
      serviceBinder.AddMethod(__Method_GetJointsLimits, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmLimits>(serviceImpl.GetJointsLimits));
      serviceBinder.AddMethod(__Method_GetTemperatures, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmTemperatures>(serviceImpl.GetTemperatures));
      serviceBinder.AddMethod(__Method_GetJointGoalPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.PartId, global::Reachy.Part.Arm.ArmPosition>(serviceImpl.GetJointGoalPosition));
      serviceBinder.AddMethod(__Method_SetSpeedLimit, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Part.Arm.SpeedLimitRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SetSpeedLimit));
    }

  }
}
#endregion
