// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: orbita2d.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Component.Orbita2D {
  public static partial class Orbita2dService
  {
    static readonly string __ServiceName = "component.orbita2d.Orbita2dService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita2D.ListOfOrbita2d> __Marshaller_component_orbita2d_ListOfOrbita2d = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita2D.ListOfOrbita2d.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita2D.Orbita2dStateRequest> __Marshaller_component_orbita2d_Orbita2dStateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita2D.Orbita2dStateRequest.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita2D.Orbita2dState> __Marshaller_component_orbita2d_Orbita2dState = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita2D.Orbita2dState.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita2D.Orbita2dStreamStateRequest> __Marshaller_component_orbita2d_Orbita2dStreamStateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita2D.Orbita2dStreamStateRequest.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita2D.Orbita2dsCommand> __Marshaller_component_orbita2d_Orbita2dsCommand = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita2D.Orbita2dsCommand.Parser));
    static readonly grpc::Marshaller<global::Component.ComponentId> __Marshaller_component_ComponentId = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.ComponentId.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita2D.Orbita2dStatus> __Marshaller_component_orbita2d_Orbita2dStatus = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita2D.Orbita2dStatus.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Component.Orbita2D.ListOfOrbita2d> __Method_GetAllOrbita2d = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Component.Orbita2D.ListOfOrbita2d>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllOrbita2d",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_component_orbita2d_ListOfOrbita2d);

    static readonly grpc::Method<global::Component.Orbita2D.Orbita2dStateRequest, global::Component.Orbita2D.Orbita2dState> __Method_GetState = new grpc::Method<global::Component.Orbita2D.Orbita2dStateRequest, global::Component.Orbita2D.Orbita2dState>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetState",
        __Marshaller_component_orbita2d_Orbita2dStateRequest,
        __Marshaller_component_orbita2d_Orbita2dState);

    static readonly grpc::Method<global::Component.Orbita2D.Orbita2dStreamStateRequest, global::Component.Orbita2D.Orbita2dState> __Method_StreamState = new grpc::Method<global::Component.Orbita2D.Orbita2dStreamStateRequest, global::Component.Orbita2D.Orbita2dState>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StreamState",
        __Marshaller_component_orbita2d_Orbita2dStreamStateRequest,
        __Marshaller_component_orbita2d_Orbita2dState);

    static readonly grpc::Method<global::Component.Orbita2D.Orbita2dsCommand, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SendCommand = new grpc::Method<global::Component.Orbita2D.Orbita2dsCommand, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendCommand",
        __Marshaller_component_orbita2d_Orbita2dsCommand,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Component.Orbita2D.Orbita2dsCommand, global::Google.Protobuf.WellKnownTypes.Empty> __Method_StreamCommand = new grpc::Method<global::Component.Orbita2D.Orbita2dsCommand, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "StreamCommand",
        __Marshaller_component_orbita2d_Orbita2dsCommand,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Component.ComponentId, global::Component.Orbita2D.Orbita2dStatus> __Method_Audit = new grpc::Method<global::Component.ComponentId, global::Component.Orbita2D.Orbita2dStatus>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Audit",
        __Marshaller_component_ComponentId,
        __Marshaller_component_orbita2d_Orbita2dStatus);

    static readonly grpc::Method<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_HeartBeat = new grpc::Method<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HeartBeat",
        __Marshaller_component_ComponentId,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Restart = new grpc::Method<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Restart",
        __Marshaller_component_ComponentId,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Component.Orbita2D.Orbita2DReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Orbita2dService</summary>
    [grpc::BindServiceMethod(typeof(Orbita2dService), "BindService")]
    public abstract partial class Orbita2dServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Component.Orbita2D.ListOfOrbita2d> GetAllOrbita2d(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Component.Orbita2D.Orbita2dState> GetState(global::Component.Orbita2D.Orbita2dStateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task StreamState(global::Component.Orbita2D.Orbita2dStreamStateRequest request, grpc::IServerStreamWriter<global::Component.Orbita2D.Orbita2dState> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SendCommand(global::Component.Orbita2D.Orbita2dsCommand request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> StreamCommand(grpc::IAsyncStreamReader<global::Component.Orbita2D.Orbita2dsCommand> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Component.Orbita2D.Orbita2dStatus> Audit(global::Component.ComponentId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeat(global::Component.ComponentId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Restart(global::Component.ComponentId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Orbita2dService</summary>
    public partial class Orbita2dServiceClient : grpc::ClientBase<Orbita2dServiceClient>
    {
      /// <summary>Creates a new client for Orbita2dService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public Orbita2dServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Orbita2dService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public Orbita2dServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected Orbita2dServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected Orbita2dServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Component.Orbita2D.ListOfOrbita2d GetAllOrbita2d(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllOrbita2d(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Component.Orbita2D.ListOfOrbita2d GetAllOrbita2d(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllOrbita2d, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita2D.ListOfOrbita2d> GetAllOrbita2dAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllOrbita2dAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita2D.ListOfOrbita2d> GetAllOrbita2dAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllOrbita2d, null, options, request);
      }
      public virtual global::Component.Orbita2D.Orbita2dState GetState(global::Component.Orbita2D.Orbita2dStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Component.Orbita2D.Orbita2dState GetState(global::Component.Orbita2D.Orbita2dStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita2D.Orbita2dState> GetStateAsync(global::Component.Orbita2D.Orbita2dStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita2D.Orbita2dState> GetStateAsync(global::Component.Orbita2D.Orbita2dStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetState, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Component.Orbita2D.Orbita2dState> StreamState(global::Component.Orbita2D.Orbita2dStreamStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Component.Orbita2D.Orbita2dState> StreamState(global::Component.Orbita2D.Orbita2dStreamStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StreamState, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SendCommand(global::Component.Orbita2D.Orbita2dsCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendCommand(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SendCommand(global::Component.Orbita2D.Orbita2dsCommand request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendCommand, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SendCommandAsync(global::Component.Orbita2D.Orbita2dsCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendCommandAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SendCommandAsync(global::Component.Orbita2D.Orbita2dsCommand request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendCommand, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::Component.Orbita2D.Orbita2dsCommand, global::Google.Protobuf.WellKnownTypes.Empty> StreamCommand(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamCommand(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Component.Orbita2D.Orbita2dsCommand, global::Google.Protobuf.WellKnownTypes.Empty> StreamCommand(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_StreamCommand, null, options);
      }
      public virtual global::Component.Orbita2D.Orbita2dStatus Audit(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Audit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Component.Orbita2D.Orbita2dStatus Audit(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Audit, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita2D.Orbita2dStatus> AuditAsync(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AuditAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita2D.Orbita2dStatus> AuditAsync(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Audit, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty HeartBeat(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HeartBeat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty HeartBeat(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HeartBeat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeatAsync(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HeartBeatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeatAsync(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HeartBeat, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Restart(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Restart(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Restart(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Restart, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RestartAsync(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RestartAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RestartAsync(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Restart, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override Orbita2dServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new Orbita2dServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(Orbita2dServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllOrbita2d, serviceImpl.GetAllOrbita2d)
          .AddMethod(__Method_GetState, serviceImpl.GetState)
          .AddMethod(__Method_StreamState, serviceImpl.StreamState)
          .AddMethod(__Method_SendCommand, serviceImpl.SendCommand)
          .AddMethod(__Method_StreamCommand, serviceImpl.StreamCommand)
          .AddMethod(__Method_Audit, serviceImpl.Audit)
          .AddMethod(__Method_HeartBeat, serviceImpl.HeartBeat)
          .AddMethod(__Method_Restart, serviceImpl.Restart).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, Orbita2dServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllOrbita2d, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Component.Orbita2D.ListOfOrbita2d>(serviceImpl.GetAllOrbita2d));
      serviceBinder.AddMethod(__Method_GetState, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.Orbita2D.Orbita2dStateRequest, global::Component.Orbita2D.Orbita2dState>(serviceImpl.GetState));
      serviceBinder.AddMethod(__Method_StreamState, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Component.Orbita2D.Orbita2dStreamStateRequest, global::Component.Orbita2D.Orbita2dState>(serviceImpl.StreamState));
      serviceBinder.AddMethod(__Method_SendCommand, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.Orbita2D.Orbita2dsCommand, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SendCommand));
      serviceBinder.AddMethod(__Method_StreamCommand, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Component.Orbita2D.Orbita2dsCommand, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.StreamCommand));
      serviceBinder.AddMethod(__Method_Audit, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.ComponentId, global::Component.Orbita2D.Orbita2dStatus>(serviceImpl.Audit));
      serviceBinder.AddMethod(__Method_HeartBeat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.HeartBeat));
      serviceBinder.AddMethod(__Method_Restart, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Restart));
    }

  }
}
#endregion
