/**
 * @fileoverview gRPC-Web generated client stub for component.dynamixel_motor
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: dynamixel_motor.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as component_pb from './component_pb';
import * as dynamixel_motor_pb from './dynamixel_motor_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';


export class DynamixelMotorServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAllDynamixelMotor = new grpcWeb.MethodDescriptor(
    '/component.dynamixel_motor.DynamixelMotorService/GetAllDynamixelMotor',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    dynamixel_motor_pb.ListOfDynamixelMotorInfo,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    dynamixel_motor_pb.ListOfDynamixelMotorInfo.deserializeBinary
  );

  getAllDynamixelMotor(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<dynamixel_motor_pb.ListOfDynamixelMotorInfo>;

  getAllDynamixelMotor(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: dynamixel_motor_pb.ListOfDynamixelMotorInfo) => void): grpcWeb.ClientReadableStream<dynamixel_motor_pb.ListOfDynamixelMotorInfo>;

  getAllDynamixelMotor(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: dynamixel_motor_pb.ListOfDynamixelMotorInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/component.dynamixel_motor.DynamixelMotorService/GetAllDynamixelMotor',
        request,
        metadata || {},
        this.methodDescriptorGetAllDynamixelMotor,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/component.dynamixel_motor.DynamixelMotorService/GetAllDynamixelMotor',
    request,
    metadata || {},
    this.methodDescriptorGetAllDynamixelMotor);
  }

  methodDescriptorGetState = new grpcWeb.MethodDescriptor(
    '/component.dynamixel_motor.DynamixelMotorService/GetState',
    grpcWeb.MethodType.UNARY,
    dynamixel_motor_pb.DynamixelMotorStateRequest,
    dynamixel_motor_pb.DynamixelMotorState,
    (request: dynamixel_motor_pb.DynamixelMotorStateRequest) => {
      return request.serializeBinary();
    },
    dynamixel_motor_pb.DynamixelMotorState.deserializeBinary
  );

  getState(
    request: dynamixel_motor_pb.DynamixelMotorStateRequest,
    metadata: grpcWeb.Metadata | null): Promise<dynamixel_motor_pb.DynamixelMotorState>;

  getState(
    request: dynamixel_motor_pb.DynamixelMotorStateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: dynamixel_motor_pb.DynamixelMotorState) => void): grpcWeb.ClientReadableStream<dynamixel_motor_pb.DynamixelMotorState>;

  getState(
    request: dynamixel_motor_pb.DynamixelMotorStateRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: dynamixel_motor_pb.DynamixelMotorState) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/component.dynamixel_motor.DynamixelMotorService/GetState',
        request,
        metadata || {},
        this.methodDescriptorGetState,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/component.dynamixel_motor.DynamixelMotorService/GetState',
    request,
    metadata || {},
    this.methodDescriptorGetState);
  }

  methodDescriptorStreamState = new grpcWeb.MethodDescriptor(
    '/component.dynamixel_motor.DynamixelMotorService/StreamState',
    grpcWeb.MethodType.SERVER_STREAMING,
    dynamixel_motor_pb.DynamixelMotorStreamStateRequest,
    dynamixel_motor_pb.DynamixelMotorState,
    (request: dynamixel_motor_pb.DynamixelMotorStreamStateRequest) => {
      return request.serializeBinary();
    },
    dynamixel_motor_pb.DynamixelMotorState.deserializeBinary
  );

  streamState(
    request: dynamixel_motor_pb.DynamixelMotorStreamStateRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<dynamixel_motor_pb.DynamixelMotorState> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/component.dynamixel_motor.DynamixelMotorService/StreamState',
      request,
      metadata || {},
      this.methodDescriptorStreamState);
  }

  methodDescriptorSendCommand = new grpcWeb.MethodDescriptor(
    '/component.dynamixel_motor.DynamixelMotorService/SendCommand',
    grpcWeb.MethodType.UNARY,
    dynamixel_motor_pb.DynamixelMotorCommand,
    google_protobuf_empty_pb.Empty,
    (request: dynamixel_motor_pb.DynamixelMotorCommand) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  sendCommand(
    request: dynamixel_motor_pb.DynamixelMotorCommand,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  sendCommand(
    request: dynamixel_motor_pb.DynamixelMotorCommand,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  sendCommand(
    request: dynamixel_motor_pb.DynamixelMotorCommand,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/component.dynamixel_motor.DynamixelMotorService/SendCommand',
        request,
        metadata || {},
        this.methodDescriptorSendCommand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/component.dynamixel_motor.DynamixelMotorService/SendCommand',
    request,
    metadata || {},
    this.methodDescriptorSendCommand);
  }

  methodDescriptorSetPosition = new grpcWeb.MethodDescriptor(
    '/component.dynamixel_motor.DynamixelMotorService/SetPosition',
    grpcWeb.MethodType.UNARY,
    dynamixel_motor_pb.DynamixelMotorGoal,
    google_protobuf_empty_pb.Empty,
    (request: dynamixel_motor_pb.DynamixelMotorGoal) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  setPosition(
    request: dynamixel_motor_pb.DynamixelMotorGoal,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  setPosition(
    request: dynamixel_motor_pb.DynamixelMotorGoal,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  setPosition(
    request: dynamixel_motor_pb.DynamixelMotorGoal,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/component.dynamixel_motor.DynamixelMotorService/SetPosition',
        request,
        metadata || {},
        this.methodDescriptorSetPosition,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/component.dynamixel_motor.DynamixelMotorService/SetPosition',
    request,
    metadata || {},
    this.methodDescriptorSetPosition);
  }

  methodDescriptorAudit = new grpcWeb.MethodDescriptor(
    '/component.dynamixel_motor.DynamixelMotorService/Audit',
    grpcWeb.MethodType.UNARY,
    component_pb.ComponentId,
    dynamixel_motor_pb.DynamixelMotorStatus,
    (request: component_pb.ComponentId) => {
      return request.serializeBinary();
    },
    dynamixel_motor_pb.DynamixelMotorStatus.deserializeBinary
  );

  audit(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null): Promise<dynamixel_motor_pb.DynamixelMotorStatus>;

  audit(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: dynamixel_motor_pb.DynamixelMotorStatus) => void): grpcWeb.ClientReadableStream<dynamixel_motor_pb.DynamixelMotorStatus>;

  audit(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: dynamixel_motor_pb.DynamixelMotorStatus) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/component.dynamixel_motor.DynamixelMotorService/Audit',
        request,
        metadata || {},
        this.methodDescriptorAudit,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/component.dynamixel_motor.DynamixelMotorService/Audit',
    request,
    metadata || {},
    this.methodDescriptorAudit);
  }

  methodDescriptorHeartBeat = new grpcWeb.MethodDescriptor(
    '/component.dynamixel_motor.DynamixelMotorService/HeartBeat',
    grpcWeb.MethodType.UNARY,
    component_pb.ComponentId,
    google_protobuf_empty_pb.Empty,
    (request: component_pb.ComponentId) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  heartBeat(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  heartBeat(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  heartBeat(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/component.dynamixel_motor.DynamixelMotorService/HeartBeat',
        request,
        metadata || {},
        this.methodDescriptorHeartBeat,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/component.dynamixel_motor.DynamixelMotorService/HeartBeat',
    request,
    metadata || {},
    this.methodDescriptorHeartBeat);
  }

  methodDescriptorRestart = new grpcWeb.MethodDescriptor(
    '/component.dynamixel_motor.DynamixelMotorService/Restart',
    grpcWeb.MethodType.UNARY,
    component_pb.ComponentId,
    google_protobuf_empty_pb.Empty,
    (request: component_pb.ComponentId) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  restart(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  restart(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  restart(
    request: component_pb.ComponentId,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/component.dynamixel_motor.DynamixelMotorService/Restart',
        request,
        metadata || {},
        this.methodDescriptorRestart,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/component.dynamixel_motor.DynamixelMotorService/Restart',
    request,
    metadata || {},
    this.methodDescriptorRestart);
  }

}

