// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: orbita3d.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Component.Orbita3D {
  public static partial class Orbita3dService
  {
    static readonly string __ServiceName = "component.orbita3d.Orbita3dService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita3D.ListOfOrbita3d> __Marshaller_component_orbita3d_ListOfOrbita3d = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita3D.ListOfOrbita3d.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita3D.Orbita3dStateRequest> __Marshaller_component_orbita3d_Orbita3dStateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita3D.Orbita3dStateRequest.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita3D.Orbita3dState> __Marshaller_component_orbita3d_Orbita3dState = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita3D.Orbita3dState.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita3D.Orbita3dStreamStateRequest> __Marshaller_component_orbita3d_Orbita3dStreamStateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita3D.Orbita3dStreamStateRequest.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita3D.Orbita3dGoal> __Marshaller_component_orbita3d_Orbita3dGoal = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita3D.Orbita3dGoal.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita3D.Orbita3dsCommand> __Marshaller_component_orbita3d_Orbita3dsCommand = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita3D.Orbita3dsCommand.Parser));
    static readonly grpc::Marshaller<global::Component.ComponentId> __Marshaller_component_ComponentId = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.ComponentId.Parser));
    static readonly grpc::Marshaller<global::Component.Orbita3D.Orbita3dStatus> __Marshaller_component_orbita3d_Orbita3dStatus = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Component.Orbita3D.Orbita3dStatus.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Component.Orbita3D.ListOfOrbita3d> __Method_GetAllOrbita3d = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Component.Orbita3D.ListOfOrbita3d>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllOrbita3d",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_component_orbita3d_ListOfOrbita3d);

    static readonly grpc::Method<global::Component.Orbita3D.Orbita3dStateRequest, global::Component.Orbita3D.Orbita3dState> __Method_GetState = new grpc::Method<global::Component.Orbita3D.Orbita3dStateRequest, global::Component.Orbita3D.Orbita3dState>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetState",
        __Marshaller_component_orbita3d_Orbita3dStateRequest,
        __Marshaller_component_orbita3d_Orbita3dState);

    static readonly grpc::Method<global::Component.Orbita3D.Orbita3dStreamStateRequest, global::Component.Orbita3D.Orbita3dState> __Method_StreamState = new grpc::Method<global::Component.Orbita3D.Orbita3dStreamStateRequest, global::Component.Orbita3D.Orbita3dState>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StreamState",
        __Marshaller_component_orbita3d_Orbita3dStreamStateRequest,
        __Marshaller_component_orbita3d_Orbita3dState);

    static readonly grpc::Method<global::Component.Orbita3D.Orbita3dGoal, global::Google.Protobuf.WellKnownTypes.Empty> __Method_GoToOrientation = new grpc::Method<global::Component.Orbita3D.Orbita3dGoal, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GoToOrientation",
        __Marshaller_component_orbita3d_Orbita3dGoal,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Component.Orbita3D.Orbita3dsCommand, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SendCommand = new grpc::Method<global::Component.Orbita3D.Orbita3dsCommand, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendCommand",
        __Marshaller_component_orbita3d_Orbita3dsCommand,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Component.Orbita3D.Orbita3dsCommand, global::Google.Protobuf.WellKnownTypes.Empty> __Method_StreamCommand = new grpc::Method<global::Component.Orbita3D.Orbita3dsCommand, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "StreamCommand",
        __Marshaller_component_orbita3d_Orbita3dsCommand,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Component.ComponentId, global::Component.Orbita3D.Orbita3dStatus> __Method_Audit = new grpc::Method<global::Component.ComponentId, global::Component.Orbita3D.Orbita3dStatus>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Audit",
        __Marshaller_component_ComponentId,
        __Marshaller_component_orbita3d_Orbita3dStatus);

    static readonly grpc::Method<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_HeartBeat = new grpc::Method<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HeartBeat",
        __Marshaller_component_ComponentId,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Restart = new grpc::Method<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Restart",
        __Marshaller_component_ComponentId,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Component.Orbita3D.Orbita3DReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Orbita3dService</summary>
    [grpc::BindServiceMethod(typeof(Orbita3dService), "BindService")]
    public abstract partial class Orbita3dServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Component.Orbita3D.ListOfOrbita3d> GetAllOrbita3d(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Component.Orbita3D.Orbita3dState> GetState(global::Component.Orbita3D.Orbita3dStateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task StreamState(global::Component.Orbita3D.Orbita3dStreamStateRequest request, grpc::IServerStreamWriter<global::Component.Orbita3D.Orbita3dState> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> GoToOrientation(global::Component.Orbita3D.Orbita3dGoal request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SendCommand(global::Component.Orbita3D.Orbita3dsCommand request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> StreamCommand(grpc::IAsyncStreamReader<global::Component.Orbita3D.Orbita3dsCommand> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Component.Orbita3D.Orbita3dStatus> Audit(global::Component.ComponentId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeat(global::Component.ComponentId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Restart(global::Component.ComponentId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Orbita3dService</summary>
    public partial class Orbita3dServiceClient : grpc::ClientBase<Orbita3dServiceClient>
    {
      /// <summary>Creates a new client for Orbita3dService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public Orbita3dServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Orbita3dService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public Orbita3dServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected Orbita3dServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected Orbita3dServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Component.Orbita3D.ListOfOrbita3d GetAllOrbita3d(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllOrbita3d(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Component.Orbita3D.ListOfOrbita3d GetAllOrbita3d(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllOrbita3d, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita3D.ListOfOrbita3d> GetAllOrbita3dAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllOrbita3dAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita3D.ListOfOrbita3d> GetAllOrbita3dAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllOrbita3d, null, options, request);
      }
      public virtual global::Component.Orbita3D.Orbita3dState GetState(global::Component.Orbita3D.Orbita3dStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Component.Orbita3D.Orbita3dState GetState(global::Component.Orbita3D.Orbita3dStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita3D.Orbita3dState> GetStateAsync(global::Component.Orbita3D.Orbita3dStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita3D.Orbita3dState> GetStateAsync(global::Component.Orbita3D.Orbita3dStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetState, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Component.Orbita3D.Orbita3dState> StreamState(global::Component.Orbita3D.Orbita3dStreamStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Component.Orbita3D.Orbita3dState> StreamState(global::Component.Orbita3D.Orbita3dStreamStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StreamState, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GoToOrientation(global::Component.Orbita3D.Orbita3dGoal request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GoToOrientation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty GoToOrientation(global::Component.Orbita3D.Orbita3dGoal request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GoToOrientation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GoToOrientationAsync(global::Component.Orbita3D.Orbita3dGoal request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GoToOrientationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> GoToOrientationAsync(global::Component.Orbita3D.Orbita3dGoal request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GoToOrientation, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SendCommand(global::Component.Orbita3D.Orbita3dsCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendCommand(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SendCommand(global::Component.Orbita3D.Orbita3dsCommand request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendCommand, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SendCommandAsync(global::Component.Orbita3D.Orbita3dsCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendCommandAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SendCommandAsync(global::Component.Orbita3D.Orbita3dsCommand request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendCommand, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::Component.Orbita3D.Orbita3dsCommand, global::Google.Protobuf.WellKnownTypes.Empty> StreamCommand(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamCommand(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Component.Orbita3D.Orbita3dsCommand, global::Google.Protobuf.WellKnownTypes.Empty> StreamCommand(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_StreamCommand, null, options);
      }
      public virtual global::Component.Orbita3D.Orbita3dStatus Audit(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Audit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Component.Orbita3D.Orbita3dStatus Audit(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Audit, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita3D.Orbita3dStatus> AuditAsync(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AuditAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Component.Orbita3D.Orbita3dStatus> AuditAsync(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Audit, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty HeartBeat(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HeartBeat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty HeartBeat(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HeartBeat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeatAsync(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HeartBeatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> HeartBeatAsync(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HeartBeat, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Restart(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Restart(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Restart(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Restart, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RestartAsync(global::Component.ComponentId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RestartAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RestartAsync(global::Component.ComponentId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Restart, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override Orbita3dServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new Orbita3dServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(Orbita3dServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllOrbita3d, serviceImpl.GetAllOrbita3d)
          .AddMethod(__Method_GetState, serviceImpl.GetState)
          .AddMethod(__Method_StreamState, serviceImpl.StreamState)
          .AddMethod(__Method_GoToOrientation, serviceImpl.GoToOrientation)
          .AddMethod(__Method_SendCommand, serviceImpl.SendCommand)
          .AddMethod(__Method_StreamCommand, serviceImpl.StreamCommand)
          .AddMethod(__Method_Audit, serviceImpl.Audit)
          .AddMethod(__Method_HeartBeat, serviceImpl.HeartBeat)
          .AddMethod(__Method_Restart, serviceImpl.Restart).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, Orbita3dServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllOrbita3d, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Component.Orbita3D.ListOfOrbita3d>(serviceImpl.GetAllOrbita3d));
      serviceBinder.AddMethod(__Method_GetState, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.Orbita3D.Orbita3dStateRequest, global::Component.Orbita3D.Orbita3dState>(serviceImpl.GetState));
      serviceBinder.AddMethod(__Method_StreamState, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Component.Orbita3D.Orbita3dStreamStateRequest, global::Component.Orbita3D.Orbita3dState>(serviceImpl.StreamState));
      serviceBinder.AddMethod(__Method_GoToOrientation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.Orbita3D.Orbita3dGoal, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.GoToOrientation));
      serviceBinder.AddMethod(__Method_SendCommand, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.Orbita3D.Orbita3dsCommand, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SendCommand));
      serviceBinder.AddMethod(__Method_StreamCommand, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Component.Orbita3D.Orbita3dsCommand, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.StreamCommand));
      serviceBinder.AddMethod(__Method_Audit, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.ComponentId, global::Component.Orbita3D.Orbita3dStatus>(serviceImpl.Audit));
      serviceBinder.AddMethod(__Method_HeartBeat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.HeartBeat));
      serviceBinder.AddMethod(__Method_Restart, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Component.ComponentId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Restart));
    }

  }
}
#endregion
