"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import error_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class AudioFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    path: builtins.str
    duration: builtins.float
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        duration: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_duration", b"_duration", "duration", b"duration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_duration", b"_duration", "duration", b"duration", "path", b"path"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_duration", b"_duration"]) -> typing_extensions.Literal["duration"] | None: ...

global___AudioFile = AudioFile

@typing_extensions.final
class AudioFiles(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILES_FIELD_NUMBER: builtins.int
    @property
    def files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AudioFile]: ...
    def __init__(
        self,
        *,
        files: collections.abc.Iterable[global___AudioFile] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["files", b"files"]) -> None: ...

global___AudioFiles = AudioFiles

@typing_extensions.final
class AudioFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    CHUNK_DATA_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> global___AudioFile: ...
    chunk_data: builtins.bytes
    def __init__(
        self,
        *,
        info: global___AudioFile | None = ...,
        chunk_data: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chunk_data", b"chunk_data", "data", b"data", "info", b"info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chunk_data", b"chunk_data", "data", b"data", "info", b"info"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["info", "chunk_data"] | None: ...

global___AudioFileRequest = AudioFileRequest

@typing_extensions.final
class AudioAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def error(self) -> error_pb2.Error: ...
    def __init__(
        self,
        *,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        error: error_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "success", b"success"]) -> None: ...

global___AudioAck = AudioAck
