"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import arm_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import head_pb2
import part_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GoalStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GoalStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GoalStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE: _GoalStatus.ValueType  # 0
    STATUS_UNKNOWN: _GoalStatus.ValueType  # 1
    STATUS_ACCEPTED: _GoalStatus.ValueType  # 2
    STATUS_EXECUTING: _GoalStatus.ValueType  # 3
    STATUS_CANCELING: _GoalStatus.ValueType  # 4
    STATUS_SUCCEEDED: _GoalStatus.ValueType  # 5
    STATUS_CANCELED: _GoalStatus.ValueType  # 6
    STATUS_ABORTED: _GoalStatus.ValueType  # 7

class GoalStatus(_GoalStatus, metaclass=_GoalStatusEnumTypeWrapper): ...

NONE: GoalStatus.ValueType  # 0
STATUS_UNKNOWN: GoalStatus.ValueType  # 1
STATUS_ACCEPTED: GoalStatus.ValueType  # 2
STATUS_EXECUTING: GoalStatus.ValueType  # 3
STATUS_CANCELING: GoalStatus.ValueType  # 4
STATUS_SUCCEEDED: GoalStatus.ValueType  # 5
STATUS_CANCELED: GoalStatus.ValueType  # 6
STATUS_ABORTED: GoalStatus.ValueType  # 7
global___GoalStatus = GoalStatus

class _InterpolationMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InterpolationModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InterpolationMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE_INTERPOLATION: _InterpolationMode.ValueType  # 0
    LINEAR: _InterpolationMode.ValueType  # 1
    MINIMUM_JERK: _InterpolationMode.ValueType  # 2

class InterpolationMode(_InterpolationMode, metaclass=_InterpolationModeEnumTypeWrapper): ...

NONE_INTERPOLATION: InterpolationMode.ValueType  # 0
LINEAR: InterpolationMode.ValueType  # 1
MINIMUM_JERK: InterpolationMode.ValueType  # 2
global___InterpolationMode = InterpolationMode

@typing_extensions.final
class GoToId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___GoToId = GoToId

@typing_extensions.final
class GoToAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_FIELD_NUMBER: builtins.int
    ack: builtins.bool
    def __init__(
        self,
        *,
        ack: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ack", b"ack"]) -> None: ...

global___GoToAck = GoToAck

@typing_extensions.final
class GoToGoalStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GOAL_STATUS_FIELD_NUMBER: builtins.int
    goal_status: global___GoalStatus.ValueType
    def __init__(
        self,
        *,
        goal_status: global___GoalStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["goal_status", b"goal_status"]) -> None: ...

global___GoToGoalStatus = GoToGoalStatus

@typing_extensions.final
class CartesianGoal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARM_CARTESIAN_GOAL_FIELD_NUMBER: builtins.int
    NECK_CARTESIAN_GOAL_FIELD_NUMBER: builtins.int
    @property
    def arm_cartesian_goal(self) -> arm_pb2.ArmCartesianGoal: ...
    @property
    def neck_cartesian_goal(self) -> head_pb2.NeckCartesianGoal: ...
    def __init__(
        self,
        *,
        arm_cartesian_goal: arm_pb2.ArmCartesianGoal | None = ...,
        neck_cartesian_goal: head_pb2.NeckCartesianGoal | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["arm_cartesian_goal", b"arm_cartesian_goal", "cartesian_goal", b"cartesian_goal", "neck_cartesian_goal", b"neck_cartesian_goal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["arm_cartesian_goal", b"arm_cartesian_goal", "cartesian_goal", b"cartesian_goal", "neck_cartesian_goal", b"neck_cartesian_goal"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["cartesian_goal", b"cartesian_goal"]) -> typing_extensions.Literal["arm_cartesian_goal", "neck_cartesian_goal"] | None: ...

global___CartesianGoal = CartesianGoal

@typing_extensions.final
class JointsGoal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARM_JOINT_GOAL_FIELD_NUMBER: builtins.int
    NECK_JOINT_GOAL_FIELD_NUMBER: builtins.int
    CUSTOM_JOINT_GOAL_FIELD_NUMBER: builtins.int
    @property
    def arm_joint_goal(self) -> arm_pb2.ArmJointGoal: ...
    @property
    def neck_joint_goal(self) -> head_pb2.NeckJointGoal: ...
    @property
    def custom_joint_goal(self) -> global___CustomJointGoal: ...
    def __init__(
        self,
        *,
        arm_joint_goal: arm_pb2.ArmJointGoal | None = ...,
        neck_joint_goal: head_pb2.NeckJointGoal | None = ...,
        custom_joint_goal: global___CustomJointGoal | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["arm_joint_goal", b"arm_joint_goal", "custom_joint_goal", b"custom_joint_goal", "joints_goal", b"joints_goal", "neck_joint_goal", b"neck_joint_goal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["arm_joint_goal", b"arm_joint_goal", "custom_joint_goal", b"custom_joint_goal", "joints_goal", b"joints_goal", "neck_joint_goal", b"neck_joint_goal"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["joints_goal", b"joints_goal"]) -> typing_extensions.Literal["arm_joint_goal", "neck_joint_goal", "custom_joint_goal"] | None: ...

global___JointsGoal = JointsGoal

@typing_extensions.final
class CustomJointGoal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ARM_JOINTS_FIELD_NUMBER: builtins.int
    NECK_JOINTS_FIELD_NUMBER: builtins.int
    JOINTS_GOALS_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> part_pb2.PartId: ...
    @property
    def arm_joints(self) -> arm_pb2.CustomArmJoints: ...
    @property
    def neck_joints(self) -> head_pb2.CustomNeckJoints: ...
    @property
    def joints_goals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.wrappers_pb2.FloatValue]: ...
    @property
    def duration(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        id: part_pb2.PartId | None = ...,
        arm_joints: arm_pb2.CustomArmJoints | None = ...,
        neck_joints: head_pb2.CustomNeckJoints | None = ...,
        joints_goals: collections.abc.Iterable[google.protobuf.wrappers_pb2.FloatValue] | None = ...,
        duration: google.protobuf.wrappers_pb2.FloatValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["arm_joints", b"arm_joints", "duration", b"duration", "id", b"id", "joints", b"joints", "neck_joints", b"neck_joints"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["arm_joints", b"arm_joints", "duration", b"duration", "id", b"id", "joints", b"joints", "joints_goals", b"joints_goals", "neck_joints", b"neck_joints"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["joints", b"joints"]) -> typing_extensions.Literal["arm_joints", "neck_joints"] | None: ...

global___CustomJointGoal = CustomJointGoal

@typing_extensions.final
class GoToInterpolation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INTERPOLATION_TYPE_FIELD_NUMBER: builtins.int
    interpolation_type: global___InterpolationMode.ValueType
    def __init__(
        self,
        *,
        interpolation_type: global___InterpolationMode.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["interpolation_type", b"interpolation_type"]) -> None: ...

global___GoToInterpolation = GoToInterpolation

@typing_extensions.final
class GoToRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARTESIAN_GOAL_FIELD_NUMBER: builtins.int
    JOINTS_GOAL_FIELD_NUMBER: builtins.int
    INTERPOLATION_MODE_FIELD_NUMBER: builtins.int
    @property
    def cartesian_goal(self) -> global___CartesianGoal: ...
    @property
    def joints_goal(self) -> global___JointsGoal: ...
    @property
    def interpolation_mode(self) -> global___GoToInterpolation: ...
    def __init__(
        self,
        *,
        cartesian_goal: global___CartesianGoal | None = ...,
        joints_goal: global___JointsGoal | None = ...,
        interpolation_mode: global___GoToInterpolation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cartesian_goal", b"cartesian_goal", "goal", b"goal", "interpolation_mode", b"interpolation_mode", "joints_goal", b"joints_goal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cartesian_goal", b"cartesian_goal", "goal", b"goal", "interpolation_mode", b"interpolation_mode", "joints_goal", b"joints_goal"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["goal", b"goal"]) -> typing_extensions.Literal["cartesian_goal", "joints_goal"] | None: ...

global___GoToRequest = GoToRequest

@typing_extensions.final
class GoToQueue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GOTO_IDS_FIELD_NUMBER: builtins.int
    @property
    def goto_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GoToId]: ...
    def __init__(
        self,
        *,
        goto_ids: collections.abc.Iterable[global___GoToId] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["goto_ids", b"goto_ids"]) -> None: ...

global___GoToQueue = GoToQueue
