# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mobile_base_lidar_pb2 as mobile__base__lidar__pb2
import mobile_base_mobility_pb2 as mobile__base__mobility__pb2
import part_pb2 as part__pb2


class MobileBaseLidarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetZuuuSafety = channel.unary_unary(
                '/reachy.part.mobile.base.lidar.MobileBaseLidarService/SetZuuuSafety',
                request_serializer=mobile__base__lidar__pb2.LidarSafety.SerializeToString,
                response_deserializer=mobile__base__mobility__pb2.MobilityServiceAck.FromString,
                )
        self.GetZuuuSafety = channel.unary_unary(
                '/reachy.part.mobile.base.lidar.MobileBaseLidarService/GetZuuuSafety',
                request_serializer=part__pb2.PartId.SerializeToString,
                response_deserializer=mobile__base__lidar__pb2.LidarSafety.FromString,
                )
        self.ResetDefaultSafetyDistances = channel.unary_unary(
                '/reachy.part.mobile.base.lidar.MobileBaseLidarService/ResetDefaultSafetyDistances',
                request_serializer=part__pb2.PartId.SerializeToString,
                response_deserializer=mobile__base__mobility__pb2.MobilityServiceAck.FromString,
                )
        self.GetLidarMap = channel.unary_unary(
                '/reachy.part.mobile.base.lidar.MobileBaseLidarService/GetLidarMap',
                request_serializer=part__pb2.PartId.SerializeToString,
                response_deserializer=mobile__base__lidar__pb2.LidarMap.FromString,
                )
        self.GetLidarObstacleDetectionStatus = channel.unary_unary(
                '/reachy.part.mobile.base.lidar.MobileBaseLidarService/GetLidarObstacleDetectionStatus',
                request_serializer=part__pb2.PartId.SerializeToString,
                response_deserializer=mobile__base__lidar__pb2.LidarObstacleDetectionStatus.FromString,
                )


class MobileBaseLidarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetZuuuSafety(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetZuuuSafety(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetDefaultSafetyDistances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLidarMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLidarObstacleDetectionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobileBaseLidarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetZuuuSafety': grpc.unary_unary_rpc_method_handler(
                    servicer.SetZuuuSafety,
                    request_deserializer=mobile__base__lidar__pb2.LidarSafety.FromString,
                    response_serializer=mobile__base__mobility__pb2.MobilityServiceAck.SerializeToString,
            ),
            'GetZuuuSafety': grpc.unary_unary_rpc_method_handler(
                    servicer.GetZuuuSafety,
                    request_deserializer=part__pb2.PartId.FromString,
                    response_serializer=mobile__base__lidar__pb2.LidarSafety.SerializeToString,
            ),
            'ResetDefaultSafetyDistances': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDefaultSafetyDistances,
                    request_deserializer=part__pb2.PartId.FromString,
                    response_serializer=mobile__base__mobility__pb2.MobilityServiceAck.SerializeToString,
            ),
            'GetLidarMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLidarMap,
                    request_deserializer=part__pb2.PartId.FromString,
                    response_serializer=mobile__base__lidar__pb2.LidarMap.SerializeToString,
            ),
            'GetLidarObstacleDetectionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLidarObstacleDetectionStatus,
                    request_deserializer=part__pb2.PartId.FromString,
                    response_serializer=mobile__base__lidar__pb2.LidarObstacleDetectionStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reachy.part.mobile.base.lidar.MobileBaseLidarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MobileBaseLidarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetZuuuSafety(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reachy.part.mobile.base.lidar.MobileBaseLidarService/SetZuuuSafety',
            mobile__base__lidar__pb2.LidarSafety.SerializeToString,
            mobile__base__mobility__pb2.MobilityServiceAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetZuuuSafety(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reachy.part.mobile.base.lidar.MobileBaseLidarService/GetZuuuSafety',
            part__pb2.PartId.SerializeToString,
            mobile__base__lidar__pb2.LidarSafety.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetDefaultSafetyDistances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reachy.part.mobile.base.lidar.MobileBaseLidarService/ResetDefaultSafetyDistances',
            part__pb2.PartId.SerializeToString,
            mobile__base__mobility__pb2.MobilityServiceAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLidarMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reachy.part.mobile.base.lidar.MobileBaseLidarService/GetLidarMap',
            part__pb2.PartId.SerializeToString,
            mobile__base__lidar__pb2.LidarMap.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLidarObstacleDetectionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reachy.part.mobile.base.lidar.MobileBaseLidarService/GetLidarObstacleDetectionStatus',
            part__pb2.PartId.SerializeToString,
            mobile__base__lidar__pb2.LidarObstacleDetectionStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
