# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import mujoco_pb2 as mujoco__pb2


class MujocoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObjectsPoses = channel.unary_unary(
                '/reachy.mujoco.MujocoService/GetObjectsPoses',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=mujoco__pb2.MujocoObjectsPoses.FromString,
                )


class MujocoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObjectsPoses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MujocoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObjectsPoses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectsPoses,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=mujoco__pb2.MujocoObjectsPoses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reachy.mujoco.MujocoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MujocoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObjectsPoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reachy.mujoco.MujocoService/GetObjectsPoses',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            mujoco__pb2.MujocoObjectsPoses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
