# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mujoco.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import kinematics_pb2 as kinematics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmujoco.proto\x12\rreachy.mujoco\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10kinematics.proto\"L\n\x10MujocoObjectPose\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x04pose\x18\x02 \x01(\x0b\x32\x1c.reachy.kinematics.Matrix4x4\"D\n\x12MujocoObjectsPoses\x12.\n\x05poses\x18\x01 \x03(\x0b\x32\x1f.reachy.mujoco.MujocoObjectPose2]\n\rMujocoService\x12L\n\x0fGetObjectsPoses\x12\x16.google.protobuf.Empty\x1a!.reachy.mujoco.MujocoObjectsPosesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mujoco_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MUJOCOOBJECTPOSE']._serialized_start=78
  _globals['_MUJOCOOBJECTPOSE']._serialized_end=154
  _globals['_MUJOCOOBJECTSPOSES']._serialized_start=156
  _globals['_MUJOCOOBJECTSPOSES']._serialized_end=224
  _globals['_MUJOCOSERVICE']._serialized_start=226
  _globals['_MUJOCOSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
