"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import component_pb2
import error_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Orbita2dField:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _Orbita2dFieldEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Orbita2dField.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE: _Orbita2dField.ValueType  # 0
    NAME: _Orbita2dField.ValueType  # 1
    ID: _Orbita2dField.ValueType  # 2
    PRESENT_POSITION: _Orbita2dField.ValueType  # 3
    PRESENT_SPEED: _Orbita2dField.ValueType  # 4
    PRESENT_LOAD: _Orbita2dField.ValueType  # 5
    TEMPERATURE: _Orbita2dField.ValueType  # 6
    JOINT_LIMITS: _Orbita2dField.ValueType  # 7
    COMPLIANT: _Orbita2dField.ValueType  # 8
    GOAL_POSITION: _Orbita2dField.ValueType  # 9
    SPEED_LIMIT: _Orbita2dField.ValueType  # 10
    TORQUE_LIMIT: _Orbita2dField.ValueType  # 11
    PID: _Orbita2dField.ValueType  # 12
    ALL: _Orbita2dField.ValueType  # 15

class Orbita2dField(_Orbita2dField, metaclass=_Orbita2dFieldEnumTypeWrapper): ...

NONE: Orbita2dField.ValueType  # 0
NAME: Orbita2dField.ValueType  # 1
ID: Orbita2dField.ValueType  # 2
PRESENT_POSITION: Orbita2dField.ValueType  # 3
PRESENT_SPEED: Orbita2dField.ValueType  # 4
PRESENT_LOAD: Orbita2dField.ValueType  # 5
TEMPERATURE: Orbita2dField.ValueType  # 6
JOINT_LIMITS: Orbita2dField.ValueType  # 7
COMPLIANT: Orbita2dField.ValueType  # 8
GOAL_POSITION: Orbita2dField.ValueType  # 9
SPEED_LIMIT: Orbita2dField.ValueType  # 10
TORQUE_LIMIT: Orbita2dField.ValueType  # 11
PID: Orbita2dField.ValueType  # 12
ALL: Orbita2dField.ValueType  # 15
global___Orbita2dField = Orbita2dField

class _Axis:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AxisEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Axis.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ROLL: _Axis.ValueType  # 0
    PITCH: _Axis.ValueType  # 1
    YAW: _Axis.ValueType  # 2

class Axis(_Axis, metaclass=_AxisEnumTypeWrapper): ...

ROLL: Axis.ValueType  # 0
PITCH: Axis.ValueType  # 1
YAW: Axis.ValueType  # 2
global___Axis = Axis

@typing_extensions.final
class Orbita2dState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    PRESENT_POSITION_FIELD_NUMBER: builtins.int
    PRESENT_SPEED_FIELD_NUMBER: builtins.int
    PRESENT_LOAD_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    JOINT_LIMITS_FIELD_NUMBER: builtins.int
    COMPLIANT_FIELD_NUMBER: builtins.int
    GOAL_POSITION_FIELD_NUMBER: builtins.int
    SPEED_LIMIT_FIELD_NUMBER: builtins.int
    TORQUE_LIMIT_FIELD_NUMBER: builtins.int
    PID_FIELD_NUMBER: builtins.int
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def id(self) -> component_pb2.ComponentId: ...
    @property
    def present_position(self) -> global___Pose2d: ...
    @property
    def present_speed(self) -> global___Vector2d: ...
    @property
    def present_load(self) -> global___Vector2d: ...
    @property
    def temperature(self) -> global___Float2d: ...
    @property
    def joint_limits(self) -> global___Limits2d: ...
    @property
    def compliant(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def goal_position(self) -> global___Pose2d: ...
    @property
    def speed_limit(self) -> global___Float2d: ...
    @property
    def torque_limit(self) -> global___Float2d: ...
    @property
    def pid(self) -> global___PID2d: ...
    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        id: component_pb2.ComponentId | None = ...,
        present_position: global___Pose2d | None = ...,
        present_speed: global___Vector2d | None = ...,
        present_load: global___Vector2d | None = ...,
        temperature: global___Float2d | None = ...,
        joint_limits: global___Limits2d | None = ...,
        compliant: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        goal_position: global___Pose2d | None = ...,
        speed_limit: global___Float2d | None = ...,
        torque_limit: global___Float2d | None = ...,
        pid: global___PID2d | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["compliant", b"compliant", "goal_position", b"goal_position", "id", b"id", "joint_limits", b"joint_limits", "pid", b"pid", "present_load", b"present_load", "present_position", b"present_position", "present_speed", b"present_speed", "speed_limit", b"speed_limit", "temperature", b"temperature", "timestamp", b"timestamp", "torque_limit", b"torque_limit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["compliant", b"compliant", "goal_position", b"goal_position", "id", b"id", "joint_limits", b"joint_limits", "pid", b"pid", "present_load", b"present_load", "present_position", b"present_position", "present_speed", b"present_speed", "speed_limit", b"speed_limit", "temperature", b"temperature", "timestamp", b"timestamp", "torque_limit", b"torque_limit"]) -> None: ...

global___Orbita2dState = Orbita2dState

@typing_extensions.final
class Orbita2dStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELDS_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Orbita2dField.ValueType]: ...
    @property
    def id(self) -> component_pb2.ComponentId: ...
    def __init__(
        self,
        *,
        fields: collections.abc.Iterable[global___Orbita2dField.ValueType] | None = ...,
        id: component_pb2.ComponentId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["fields", b"fields", "id", b"id"]) -> None: ...

global___Orbita2dStateRequest = Orbita2dStateRequest

@typing_extensions.final
class Orbita2dStreamStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQ_FIELD_NUMBER: builtins.int
    FREQ_FIELD_NUMBER: builtins.int
    @property
    def req(self) -> global___Orbita2dStateRequest: ...
    freq: builtins.float
    def __init__(
        self,
        *,
        req: global___Orbita2dStateRequest | None = ...,
        freq: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["req", b"req"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["freq", b"freq", "req", b"req"]) -> None: ...

global___Orbita2dStreamStateRequest = Orbita2dStreamStateRequest

@typing_extensions.final
class PID2d(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOTOR_1_FIELD_NUMBER: builtins.int
    MOTOR_2_FIELD_NUMBER: builtins.int
    @property
    def motor_1(self) -> component_pb2.PIDGains: ...
    @property
    def motor_2(self) -> component_pb2.PIDGains: ...
    def __init__(
        self,
        *,
        motor_1: component_pb2.PIDGains | None = ...,
        motor_2: component_pb2.PIDGains | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["motor_1", b"motor_1", "motor_2", b"motor_2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["motor_1", b"motor_1", "motor_2", b"motor_2"]) -> None: ...

global___PID2d = PID2d

@typing_extensions.final
class Limits2d(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AXIS_1_FIELD_NUMBER: builtins.int
    AXIS_2_FIELD_NUMBER: builtins.int
    @property
    def axis_1(self) -> component_pb2.JointLimits: ...
    @property
    def axis_2(self) -> component_pb2.JointLimits: ...
    def __init__(
        self,
        *,
        axis_1: component_pb2.JointLimits | None = ...,
        axis_2: component_pb2.JointLimits | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["axis_1", b"axis_1", "axis_2", b"axis_2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["axis_1", b"axis_1", "axis_2", b"axis_2"]) -> None: ...

global___Limits2d = Limits2d

@typing_extensions.final
class Pose2d(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AXIS_1_FIELD_NUMBER: builtins.int
    AXIS_2_FIELD_NUMBER: builtins.int
    @property
    def axis_1(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    @property
    def axis_2(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        axis_1: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        axis_2: google.protobuf.wrappers_pb2.FloatValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["axis_1", b"axis_1", "axis_2", b"axis_2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["axis_1", b"axis_1", "axis_2", b"axis_2"]) -> None: ...

global___Pose2d = Pose2d

@typing_extensions.final
class Float2d(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOTOR_1_FIELD_NUMBER: builtins.int
    MOTOR_2_FIELD_NUMBER: builtins.int
    @property
    def motor_1(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    @property
    def motor_2(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        motor_1: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        motor_2: google.protobuf.wrappers_pb2.FloatValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["motor_1", b"motor_1", "motor_2", b"motor_2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["motor_1", b"motor_1", "motor_2", b"motor_2"]) -> None: ...

global___Float2d = Float2d

@typing_extensions.final
class Vector2d(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    @property
    def x(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    @property
    def y(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        x: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        y: google.protobuf.wrappers_pb2.FloatValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___Vector2d = Vector2d

@typing_extensions.final
class Orbita2dCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    COMPLIANT_FIELD_NUMBER: builtins.int
    GOAL_POSITION_FIELD_NUMBER: builtins.int
    SPEED_LIMIT_FIELD_NUMBER: builtins.int
    TORQUE_LIMIT_FIELD_NUMBER: builtins.int
    PID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> component_pb2.ComponentId: ...
    @property
    def compliant(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def goal_position(self) -> global___Pose2d: ...
    @property
    def speed_limit(self) -> global___Float2d: ...
    @property
    def torque_limit(self) -> global___Float2d: ...
    @property
    def pid(self) -> global___PID2d: ...
    def __init__(
        self,
        *,
        id: component_pb2.ComponentId | None = ...,
        compliant: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        goal_position: global___Pose2d | None = ...,
        speed_limit: global___Float2d | None = ...,
        torque_limit: global___Float2d | None = ...,
        pid: global___PID2d | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["compliant", b"compliant", "goal_position", b"goal_position", "id", b"id", "pid", b"pid", "speed_limit", b"speed_limit", "torque_limit", b"torque_limit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["compliant", b"compliant", "goal_position", b"goal_position", "id", b"id", "pid", b"pid", "speed_limit", b"speed_limit", "torque_limit", b"torque_limit"]) -> None: ...

global___Orbita2dCommand = Orbita2dCommand

@typing_extensions.final
class Orbita2dsCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CMD_FIELD_NUMBER: builtins.int
    @property
    def cmd(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Orbita2dCommand]: ...
    def __init__(
        self,
        *,
        cmd: collections.abc.Iterable[global___Orbita2dCommand] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cmd", b"cmd"]) -> None: ...

global___Orbita2dsCommand = Orbita2dsCommand

@typing_extensions.final
class Orbita2d(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: builtins.int
    AXIS_1_FIELD_NUMBER: builtins.int
    AXIS_2_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> component_pb2.ComponentId: ...
    serial_number: builtins.str
    axis_1: global___Axis.ValueType
    axis_2: global___Axis.ValueType
    def __init__(
        self,
        *,
        id: component_pb2.ComponentId | None = ...,
        serial_number: builtins.str = ...,
        axis_1: global___Axis.ValueType = ...,
        axis_2: global___Axis.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["axis_1", b"axis_1", "axis_2", b"axis_2", "id", b"id", "serial_number", b"serial_number"]) -> None: ...

global___Orbita2d = Orbita2d

@typing_extensions.final
class ListOfOrbita2d(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORBITA2D_FIELD_NUMBER: builtins.int
    @property
    def orbita2d(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Orbita2d]: ...
    def __init__(
        self,
        *,
        orbita2d: collections.abc.Iterable[global___Orbita2d] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["orbita2d", b"orbita2d"]) -> None: ...

global___ListOfOrbita2d = ListOfOrbita2d

@typing_extensions.final
class Orbita2dStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERRORS_FIELD_NUMBER: builtins.int
    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[error_pb2.Error]: ...
    def __init__(
        self,
        *,
        errors: collections.abc.Iterable[error_pb2.Error] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["errors", b"errors"]) -> None: ...

global___Orbita2dStatus = Orbita2dStatus
