
name: Generate Protobuf C# Code

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build solution
      run: msbuild 'csharp\reachy_sdk\reachy_sdk.sln'

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Generated Protobuf C# Code" || echo "No changes to commit"
        git push